apiVersion: v1
kind: Pod
metadata:
  name: krr
spec:
  containers:
    - image: cloudrepo-docker-playground.jfrog.io/user-rconti/krr:1.0.4
      name: krr
      volumeMounts:
      - mountPath: /output
        name: logs-krr
  volumes:
    - name: "logs-krr"
      emptyDir: {}
